# Generated by Django 4.2.18 on 2025-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default='3112d979d7b943ebb8a36f37955c6063', max_length=32, unique=True, verbose_name='Código'),
        ),
    ]
