# Generated by Django 4.2.18 on 2025-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default='9f5765d7e9d04b2fb0c08db4add685ad', max_length=32, unique=True, verbose_name='Código'),
        ),
    ]
