# Generated by Django 4.2.18 on 2025-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default='35ba4d0f53d94c9baacf1ec4f27052f8', max_length=32, unique=True, verbose_name='Código'),
        ),
    ]
