# Generated by Django 4.2.18 on 2025-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='CQISA'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default='74920e71030b469cb73a4694d872bc0a', max_length=32, unique=True, verbose_name='Código'),
        ),
    ]
